development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://fogatta-faye.herokuapp.com/faye"
  secret_token: "anything"
  signature_expiration: 3600 # one hour
