development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: <%= ENV['FAYE_SERVER'] %>
  secret_token: <%= ENV['FAYE_PASSWORD'] %>
  signature_expiration: 3600 # one hour
